In [149]:
import pandas as pd
import numpy as np

In [150]:
df=pd.read_csv('Restaurant_Reviews.tsv',sep = '\t')
df.head()

Review  Liked
0                           Wow... Loved this place.      1
1                                 Crust is not good.      0
2          Not tasty and the texture was just nasty.      0
3  Stopped by during the late May bank holiday of...      1
4  The selection on the menu was great and so wer...      1

In [151]:
df.notna().sum()

Review    1000
Liked     1000
dtype: int64

In [152]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Review  1000 non-null   object
 1   Liked   1000 non-null   int64 
dtypes: int64(1), object(1)
memory usage: 15.8+ KB


In [153]:
x=df['Review']

In [154]:
x

0                               Wow... Loved this place.
1                                     Crust is not good.
2              Not tasty and the texture was just nasty.
3      Stopped by during the late May bank holiday of...
4      The selection on the menu was great and so wer...
                             ...                        
995    I think food should have flavor and texture an...
996                             Appetite instantly gone.
997    Overall I was not impressed and would not go b...
998    The whole experience was underwhelming, and I ...
999    Then, as if I hadn't wasted enough of my life ...
Name: Review, Length: 1000, dtype: object

In [155]:
y=df['Liked']

In [156]:
y

0      1
1      0
2      0
3      1
4      1
      ..
995    0
996    0
997    0
998    0
999    0
Name: Liked, Length: 1000, dtype: int64

In [157]:
from keras.preprocessing.text import Tokenizer
tokenizer=Tokenizer(oov_token='<nothing>')

In [158]:
tokenizer.fit_on_texts(x)

In [159]:
tokenizer.word_index

{'<nothing>': 1,
 'the': 2,
 'and': 3,
 'i': 4,
 'was': 5,
 'a': 6,
 'to': 7,
 'is': 8,
 'this': 9,
 'it': 10,
 'of': 11,
 'food': 12,
 'not': 13,
 'for': 14,
 'in': 15,
 'place': 16,
 'good': 17,
 'service': 18,
 'we': 19,
 'very': 20,
 'my': 21,
 'with': 22,
 'great': 23,
 'had': 24,
 'that': 25,
 'be': 26,
 'so': 27,
 'were': 28,
 'are': 29,
 'but': 30,
 'have': 31,
 'back': 32,
 'you': 33,
 'here': 34,
 'they': 35,
 'on': 36,
 'at': 37,
 'like': 38,
 'go': 39,
 'all': 40,
 'time': 41,
 'our': 42,
 'will': 43,
 'there': 44,
 'as': 45,
 'really': 46,
 'just': 47,
 'an': 48,
 'their': 49,
 'if': 50,
 'best': 51,
 'would': 52,
 'ever': 53,
 'also': 54,
 'friendly': 55,
 'up': 56,
 'only': 57,
 'never': 58,
 'one': 59,
 'no': 60,
 'your': 61,
 'restaurant': 62,
 'out': 63,
 'nice': 64,
 "don't": 65,
 'been': 66,
 'what': 67,
 'amazing': 68,
 'again': 69,
 'from': 70,
 'delicious': 71,
 'vegas': 72,
 'did': 73,
 'by': 74,
 'which': 75,
 'pretty': 76,
 'some': 77,
 'me': 78,
 'came': 79,


In [160]:
tokenizer.word_counts

OrderedDict([('wow', 3),
             ('loved', 10),
             ('this', 143),
             ('place', 106),
             ('crust', 2),
             ('is', 171),
             ('not', 116),
             ('good', 95),
             ('tasty', 11),
             ('and', 393),
             ('the', 585),
             ('texture', 3),
             ('was', 295),
             ('just', 35),
             ('nasty', 3),
             ('stopped', 2),
             ('by', 21),
             ('during', 5),
             ('late', 2),
             ('may', 5),
             ('bank', 1),
             ('holiday', 1),
             ('off', 9),
             ('rick', 1),
             ('steve', 1),
             ('recommendation', 3),
             ('it', 134),
             ('selection', 10),
             ('on', 55),
             ('menu', 15),
             ('great', 70),
             ('so', 66),
             ('were', 63),
             ('prices', 10),
             ('now', 12),
             ('i', 305),
             ('am',

In [161]:
tokenizer.document_count

1000

In [162]:
sequences=tokenizer.texts_to_sequences(x)
sequences

[[429, 166, 9, 16],
 [587, 8, 13, 17],
 [13, 152, 3, 2, 430, 5, 47, 431],
 [588, 74, 293, 2, 589, 294, 899, 900, 181, 901, 902, 432, 3, 166, 10],
 [2, 167, 36, 2, 110, 5, 23, 3, 27, 28, 2, 168],
 [141, 4, 263, 202, 903, 3, 4, 132, 21, 351, 264],
 [904, 10, 133, 134, 25, 123],
 [2,
  433,
  28,
  38,
  905,
  3,
  33,
  106,
  265,
  35,
  24,
  66,
  101,
  56,
  906,
  11,
  41,
  124,
  295,
  434,
  6,
  907],
 [2, 182, 28, 23, 111],
 [6, 23, 590],
 [18, 5, 20, 908],
 [52, 13, 39, 32],
 [2,
  591,
  24,
  60,
  435,
  67,
  27,
  53,
  36,
  67,
  4,
  24,
  7,
  107,
  10,
  153,
  592,
  56,
  124,
  909,
  234],
 [4, 235, 2, 910, 911, 912, 102, 22, 913, 593],
 [4, 5, 914, 125, 4, 5, 76, 203, 25, 5, 594, 595],
 [4, 5, 915, 125, 60, 916, 917, 918, 57],
 [352, 436],
 [204, 5, 6, 169, 154, 15, 18],
 [9, 16, 8, 13, 170, 61, 41, 596, 919, 72],
 [73, 13, 38, 37, 40],
 [2, 920, 921],
 [2, 12, 68],
 [18, 8, 54, 597],
 [4, 106, 435, 922, 2, 923, 8, 47, 437],
 [27, 35, 924],
 [925, 183, 2, 

In [163]:
from keras.utils import pad_sequences
from keras.layers import LSTM
from keras.layers import Embedding

In [164]:
sent_length=50

In [165]:
sequences=pad_sequences(sequences,padding='post',maxlen=sent_length)

In [166]:
sequences

array([[429, 166,   9, ...,   0,   0,   0],
       [587,   8,  13, ...,   0,   0,   0],
       [ 13, 152,   3, ...,   0,   0,   0],
       ...,
       [208,   4,   5, ...,   0,   0,   0],
       [  2, 834,  82, ...,   0,   0,   0],
       [201,  45,  50, ...,   0,   0,   0]], dtype=int32)

In [167]:
len(sequences[999])

50

In [168]:
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten
from keras.layers import Dropout

In [169]:
embedding__vector_features=40
voc_size=5000

In [170]:
model=Sequential()

In [171]:
from keras.layers.normalization.batch_normalization_v1 import BatchNormalization
model.add(Embedding(voc_size,embedding__vector_features,input_length=sent_length))
model.add(BatchNormalization())
model.add(Dropout(0.2))


In [172]:
model.add(LSTM(100))
model.add(BatchNormalization())
model.add(Dropout(0.2))

In [173]:
model.add(Dense(1,activation='sigmoid'))

In [174]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])


In [175]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_4 (Embedding)     (None, 50, 40)            200000    
                                                                 
 batch_normalization_4 (Batc  (None, 50, 40)           160       
 hNormalization)                                                 
                                                                 
 dropout_4 (Dropout)         (None, 50, 40)            0         
                                                                 
 lstm_4 (LSTM)               (None, 100)               56400     
                                                                 
 batch_normalization_5 (Batc  (None, 100)              400       
 hNormalization)                                                 
                                                                 
 dropout_5 (Dropout)         (None, 100)              

In [176]:
x_final=np.array(sequences)
y_final=np.array(y)

In [177]:
x_final.shape,y_final.shape

((1000, 50), (1000,))

In [178]:
from sklearn.model_selection import train_test_split

In [179]:
x_train,x_test,y_train,y_test=train_test_split(x_final,y_final,test_size=0.3,random_state=22)

In [180]:
model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=20,batch_size=32)

Epoch 1/20
22/22 [==============================] - 6s 101ms/step - loss: 0.7277 - accuracy: 0.4929 - val_loss: 0.6931 - val_accuracy: 0.5067
Epoch 2/20
22/22 [==============================] - 2s 74ms/step - loss: 0.7021 - accuracy: 0.5057 - val_loss: 0.6930 - val_accuracy: 0.5100
Epoch 3/20
22/22 [==============================] - 2s 102ms/step - loss: 0.5772 - accuracy: 0.6643 - val_loss: 0.7046 - val_accuracy: 0.4933
Epoch 4/20
22/22 [==============================] - 1s 67ms/step - loss: 0.2831 - accuracy: 0.8971 - val_loss: 0.6924 - val_accuracy: 0.4933
Epoch 5/20
22/22 [==============================] - 1s 63ms/step - loss: 0.1949 - accuracy: 0.9386 - val_loss: 0.6713 - val_accuracy: 0.5367
Epoch 6/20
22/22 [==============================] - 1s 62ms/step - loss: 0.0659 - accuracy: 0.9786 - val_loss: 0.5721 - val_accuracy: 0.7167
Epoch 7/20
22/22 [==============================] - 2s 69ms/step - loss: 0.1111 - accuracy: 0.9671 - val_loss: 0.6182 - val_accuracy: 0.6233
Epoch 8/20


In [181]:
y_pred=model.predict(x_test)

10/10 [==============================] - 1s 15ms/step


In [182]:
y_pred[30]

array([0.992325], dtype=float32)

In [183]:
y_pred = model.predict(x_test)
y_pred = np.round(y_pred).astype(int)

10/10 [==============================] - 0s 17ms/step


In [184]:
from sklearn.metrics import confusion_matrix

In [185]:
confusion_matrix(y_test,y_pred)

array([[113,  35],
       [ 33, 119]])

In [186]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7733333333333333